Routine update at Tue Mar 19 20:20:22 HKT 2024

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,135 +1,270 @@
 #!/bin/bash
-set -o pipefail
+# set -o pipefail
 #==============================================================#
 # File      :   install
-# Desc      :   get latest stable pigsty source code
+# Desc      :   download & install pigsty
 # Ctime     :   2022-10-30
 # Mtime     :   2023-08-19
-# Path      :   https://get.pigsty.cc/latest
-# Usage     :   bash -c "$(curl -fsSL https://get.pigsty.cc/latest)"
+# Path      :   https://pigsty.io/install
+# Usage     :   bash -c "$(curl -fsSL https://pigsty.io/install)"
 # Deps      :   curl
 # Author    :   Ruohang Feng (rh@vonng.com)
 # License   :   AGPLv3
 #==============================================================#
-VERSION=${VERSION-'v2.6.0'}
 
 
 #--------------------------------------------------------------#
-# Usage
+# Log Util
 #--------------------------------------------------------------#
-# bash -c "$(curl -fsSL https://get.pigsty.cc/latest)"               # get from CDN or Github
-# SOURCE=GITHUB bash -c "$(curl -fsSL https://get.pigsty.cc/latest)"  # enforce download from github
-# SOURCE=CDN    bash -c "$(curl -fsSL https://get.pigsty.cc/latest)"  # enforce download from CDN
-
-
-#--------------------------------------------------------------#
-# Param
-#--------------------------------------------------------------#
-SOURCE_FILENAME="pigsty-${VERSION}.tgz"
-SOURCE_URL_GITHUB="https://github.com/Vonng/pigsty/releases/download/${VERSION}/${SOURCE_FILENAME}"
-SOURCE_URL_CDN="https://get.pigsty.cc/${VERSION}/${SOURCE_FILENAME}"
-SOURCE_URL=${SOURCE_URL_GITHUB}
-DOWNLOAD_TO="/tmp/${SOURCE_FILENAME}"
-EXTRACT_TO="${HOME}/pigsty"
-
-
-#--------------------------------------------------------------#
-# Utils
-#--------------------------------------------------------------#
-__CN='\033[0m';__CB='\033[0;30m';__CR='\033[0;31m';__CG='\033[0;32m';
-__CY='\033[0;33m';__CB='\033[0;34m';__CM='\033[0;35m';__CC='\033[0;36m';__CW='\033[0;37m';
-function log_info() {  printf "[${__CG} OK ${__CN}] ${__CG}$*${__CN}\n";   }
-function log_warn() {  printf "[${__CY}WARN${__CN}] ${__CY}$*${__CN}\n";   }
-function log_error() { printf "[${__CR}FAIL${__CN}] ${__CR}$*${__CN}\n";   }
+# if output is a terminal, setup color alias, else use empty str
+if [[ -t 1 ]]; then
+    __CN='\033[0m';__CB='\033[0;30m';__CR='\033[0;31m';__CG='\033[0;32m';
+    __CY='\033[0;33m';__CB='\033[0;34m';__CM='\033[0;35m';__CC='\033[0;36m';__CW='\033[0;37m';
+else
+    __CN='';__CB='';__CR='';__CG='';__CY='';__CB='';__CM='';__CC='';__CW='';
+fi
+function log_info()  { printf "[${__CG} OK ${__CN}] ${__CG}$*${__CN}\n"; }
+function log_warn()  { printf "[${__CY}WARN${__CN}] ${__CY}$*${__CN}\n"; }
+function log_error() { printf "[${__CR}FAIL${__CN}] ${__CR}$*${__CN}\n"; }
+function log_red()   { printf "[${__CR}WARN${__CN}] ${__CR}$*${__CN}\n"; }
 function log_debug() { printf "[${__CB}HINT${__CN}] ${__CB}$*${__CN}\n"; }
+function log_title() { printf "[${__CG}$1${__CN}] ${__CG}$2${__CN}\n";   }
 function log_hint()  { printf "${__CB}$*${__CN}\n"; }
 function log_line()  { printf "${__CM}[$*] ===========================================${__CN}\n"; }
-function behind_gfw() {
-    local return_code=$(curl -I -s --connect-timeout 1 www.google.com -w %{http_code} | tail -n1)
-    if [ "${return_code}" = "200" ]; then
-        return 1
+
+
+#--------------------------------------------------------------#
+# Version
+#--------------------------------------------------------------#
+DEFAULT_VERSION=v2.6.0
+VALID_VERSIONS="\
+v1.0.0 v1.1.1 v1.2.0 v1.3.0 v1.4.0 v1.4.1 v1.5.0 v1.5.1 v2.0.0 \
+v2.0.1 v2.0.2 v2.1.0 v2.2.0 v2.3.0 v2.3.1 v2.4.0 v2.4.1 v2.5.0 v2.5.1 v2.6.0"
+VERSION=${DEFAULT_VERSION}
+VERSION_FROM="default"
+KERNEL=$(uname)
+ARCH=$(uname -m)
+
+# arg1 > env > default
+if [[ -n "$1" ]]; then
+    VERSION=$1
+    VERSION_FROM="arg"
+fi
+
+function check_version(){
+    local found=false
+
+    # validate version format
+    if [[ ! ${VERSION} =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-z]+[0-9]+)?$ ]]; then
+        log_error "invalid version string from ${VERSION_FROM}: ${VERSION}"
+        exit 1
     fi
-    return 0
+
+    # check version in table
+    for ver in ${VALID_VERSIONS}; do
+        if [ "${ver}" = "${VERSION}" ]; then
+            found="true"
+            break
+        fi
+    done
+
+    # print version string if valid
+    if [[ "${found}" != "true" ]]; then
+        log_error "invalid version from ${VERSION_FROM}: ${VERSION}"
+        log_hint "valid pigsty versions:"
+        for ver in ${VALID_VERSIONS}; do
+            log_hint "  - ${ver}"
+        done
+        exit 1
+    fi
 }
 
+check_version
+
 
 #--------------------------------------------------------------#
-# Check Environment (determine where to download pigsty source)
+# Reference
 #--------------------------------------------------------------#
-log_line "Checking"
-if [[ -n "${SOURCE}" ]]; then
-    if [[ "${SOURCE}" == "GITHUB" || "${SOURCE}" == "CDN" ]]; then
-       log_info "SOURCE=${SOURCE} from environment"
-       if [[ "${SOURCE}" == "CDN" ]]; then
-           SOURCE_URL=${SOURCE_URL_CDN}
-       fi
-    else
-       log_error "invalid environment SOURCE=${SOURCE}, use 'CDN' or 'GITHUB'"
-       log_hint '$ SOURCE=GITHUB bash -c "$(curl -fsSL https://get.pigsty.cc/latest);"'
-       log_hint '$ SOURCE=CDN    bash -c "$(curl -fsSL https://get.pigsty.cc/latest);"'
-       exit 1
-    fi
-else
-    if behind_gfw; then
-        log_info "SOURCE from CDN due to GFW"
-        SOURCE="CDN"
-        SOURCE_URL=${SOURCE_URL_CDN}
-    else
-        log_info "SOURCE from GITHUB Release"
-        SOURCE="GITHUB"
-    fi
-fi
-log_hint 'FROM CDN    : bash -c "$(curl -fsSL https://get.pigsty.cc/latest)"'
-log_hint 'FROM GITHUB : bash -c "$(curl -fsSL https://raw.githubusercontent.com/Vonng/pigsty/master/bin/latest)"'
+log_line "${VERSION}"
+log_hint "$ curl -fsSL https://pigsty.cc/install | bash"
+log_title "Site" "https://pigsty.io"
+log_title "Demo" "https://demo.pigsty.cc"
+log_title "Repo" "https://github.com/Vonng/pigsty"
+log_title "Docs" "https://pigsty.io/docs/setup/install"
+
+# the VERSION is set and checked after this
+log_line "Download"
+
+log_info "version = ${VERSION} (from ${VERSION_FROM})"
 
 
 #--------------------------------------------------------------#
 # Download
 #--------------------------------------------------------------#
-log_line "Downloading"
-log_info "download pigsty source code from ${SOURCE}"
-log_info "$ curl -SL ${SOURCE_URL}"
-curl -SL "${SOURCE_URL}" -o "${DOWNLOAD_TO}"
+SITE="https://repo.pigsty.io"
+SOURCE_FILENAME="pigsty-${VERSION}.tgz"
+SOURCE_URL="${SITE}/pkg/${SOURCE_FILENAME}"
+DOWNLOAD_TO="/tmp/${SOURCE_FILENAME}"
+
+# download file from url, if file already exists with same size, skip download
+function download_file(){
+    local data_url=$1
+    local data_file=$2
+
+    log_hint "curl -fSL ${data_url} -o ${data_file}"
+    # if file exists and have the exact same size, just use it and skip downloading
+    if [[ -f ${data_file} ]]; then
+        if [[ "$(uname)" == "Darwin" ]]; then
+            size=$(stat -f %z "${data_file}")
+        else
+            size=$(stat -c %s "${data_file}")
+        fi
+        curl_size=$(curl -fsLI ${data_url} | grep -i 'Content-Length' | awk '{print $2}' | tr -d '\r')
+        if [[ ${size} -eq ${curl_size} ]]; then
+        log_warn "tarball = ${data_file} exists, size = ${size}, use it"
+        #log_hint "rm -rf ${data_file};  # remove it to redownload source tarball"
+        return 0
+        fi
+    fi
+    curl -# -fSL ${data_url} -o ${data_file}
+    return $?
+}
+
+download_file "${SOURCE_URL}" "${DOWNLOAD_TO}"
 if [[ $? -ne 0 ]]; then
-    log_error "fail to download pigsty source from ${SOURCE}"
-    log_info "check https://pigsty.io/en/docs/install , or try with CDN/GITHUB"
-    log_hint '$ SOURCE=CDN    bash -c "$(curl -fsSL https://get.pigsty.cc/latest);"'
-    log_hint '$ SOURCE=GITHUB bash -c "$(curl -fsSL https://get.pigsty.cc/latest);"'
+    log_error "fail to download pigsty source from ${SOURCE_URL}"
+    log_hint "check: https://pigsty.io/docs/setup/install"
     exit 2
 fi
-# get md5 checksum of ${DOWNLOAD_TO}
-log_hint "MD5: $(md5sum ${DOWNLOAD_TO})"
+log_info "md5sums = $(md5sum ${DOWNLOAD_TO})"
+
 
 
 #--------------------------------------------------------------#
-# Extract
+# Install
 #--------------------------------------------------------------#
-log_line "Extracting"
+INSTALL_TO="${HOME}/pigsty"
+INSTALL_DIR=$(dirname ${INSTALL_TO})
+
+log_line "Install"
+if [[ $(whoami) == "root" ]]; then
+    log_warn "os user = root , it's recommneded to install as a sudo-able admin"
+fi
+
 # extract to home dir if ~/pigsty not exists
-if [[ ! -d ${EXTRACT_TO} ]]; then
-    log_info "extract '${DOWNLOAD_TO}' to '${EXTRACT_TO}'"
-    log_info "$ tar -xf ${DOWNLOAD_TO} -C ~;"
-    tar -xf ${DOWNLOAD_TO} -C ~;
+if [[ ! -d ${INSTALL_TO} ]]; then
+    log_info "install = ${INSTALL_TO} ,from ${DOWNLOAD_TO}"
+    tar -xf "${DOWNLOAD_TO}" -C "${INSTALL_DIR}";
 else
-    log_warn "${EXTRACT_TO} already exists, you can backup old pigsty dir and overwrite it with:"
-    log_hint "rm -rf /tmp/pigsty_backup; mv -f ${EXTRACT_TO} /tmp/pigsty_backup;"
-    log_hint "cd ~; rm -rf ~/pigsty; tar -xf ${DOWNLOAD_TO} -C ."
-    log_hint "cat /tmp/pigsty_backup/pigsty.yml > ~/pigsty/pigsty.yml;"
-    log_hint "rm -rf files/pki; cp -r /tmp/pigsty_backup/files/pki ~/pigsty/files/pki"
+    log_warn "pigsty already installed on '${INSTALL_TO}', if you wish to overwrite:"
+    log_hint "sudo rm -rf /tmp/pigsty_bk; cp -r ${INSTALL_TO} /tmp/pigsty_bk; # backup old"
+    log_hint "sudo rm -rf /tmp/pigsty;    tar -xf ${DOWNLOAD_TO} -C /tmp/; # extract new"
+    log_hint "rsync -av --exclude='/pigsty.yml' --exclude='/files/pki/***' /tmp/pigsty/ ${INSTALL_TO}/; # rsync src"
+fi
+
+
+
+#--------------------------------------------------------------#
+# OS Info
+#--------------------------------------------------------------#
+# Print optional offline package info if application to current kernel, arch, os, distro
+OS_VENDOR=""
+OS_VERSION=""
+OS_PACKAGE=""
+OS_MANAGER=""
+OS_CODENAME=""
+
+PIGSTY_VERSION=${VERSION}
+
+function check_os(){
+    if [[ "$(uname)" == "Darwin" ]]; then
+        OS_VENDOR="MacOS"
+        return 0
+    fi
+
+    if [[ -f /etc/os-release ]]; then
+        . /etc/os-release
+        OS_VENDOR="$ID"
+        OS_VERSION="$VERSION_ID"
+        OS_CODENAME=${VERSION_CODENAME-''}
+        if [[ $VERSION_ID == *.* ]]; then
+            OS_VERSION=$(echo "$VERSION_ID" | cut -d. -f1)
+        else
+            OS_VERSION="${VERSION_ID}"
+        fi
+    else
+        OS_VENDOR="unknown"
+        OS_VERSION="unknown"
+    fi
+
+    # get package / manager: rpm|deb and dnf|yum|apt|apt-get|zypper
+    if command -v dpkg >/dev/null 2>&1; then
+        OS_PACKAGE="deb"
+        if command -v apt >/dev/null 2>&1; then
+            OS_MANAGER="apt"
+        elif command -v apt-get >/dev/null 2>&1; then
+            OS_MANAGER="apt-get"
+        else
+            OS_MANAGER="unknown"
+        fi
+    elif command -v rpm >/dev/null 2>&1; then
+        OS_PACKAGE="rpm"
+        if command -v dnf >/dev/null 2>&1; then
+            OS_MANAGER="dnf"
+        elif command -v yum >/dev/null 2>&1; then
+            OS_MANAGER="yum"
+        elif command -v zypper >/dev/null 2>&1; then
+            OS_MANAGER="zypper"
+        else
+            OS_MANAGER="unknown"
+        fi
+    else
+        OS_PACKAGE="unknown"
+        OS_MANAGER="unknown"
+    fi
+}
+
+check_os
+
+PKG_FILENAME=""
+PKG_BASEURL="https://github.com/Vonng/pigsty/releases/download/${PIGSTY_VERSION}"
+
+function check_offline_pkg_available(){
+    if [[ ${KERNEL} != "Linux" || ${ARCH} != "x86_64" ]]; then
+        return 0
+    fi
+
+    # EL 7,8,9 & Debian 11,12 & Ubuntu 20/22
+    if [[ ${OS_PACKAGE} == "rpm" ]]; then
+        if [[ ${OS_VERSION} == "7" || ${OS_VERSION} == "8" || ${OS_VERSION} == "9" ]]; then
+            PKG_FILENAME="pigsty-pkg-${PIGSTY_VERSION}.el${OS_VERSION}.x86_64.tgz"
+        fi
+    elif [[ ${OS_PACKAGE} == "deb" ]]; then
+        if [[ ${OS_CODENAME} == "jammy" || ${OS_CODENAME} == "focal" || ${OS_CODENAME} == "bookworm" || ${OS_CODENAME} == "bullseye" ]]; then
+            PKG_FILENAME="pigsty-pkg-${PIGSTY_VERSION}.${OS_VENDOR}${OS_VERSION}.x86_64.tgz"
+        fi
+    fi
+}
+
+check_offline_pkg_available
+
+if [[ ${PKG_FILENAME} != "" ]]; then
+    PKG_URL="${PKG_BASEURL}/${PKG_FILENAME}"
+
+    log_title "Info" "${OS_VENDOR} ${OS_VERSION} ${OS_CODENAME} has [OPTIONAL] offline package available, https://pigsty.io/docs/setup/offline"
+    log_hint "curl -fSL ${PKG_URL} -o /tmp/pkg.tgz"
+    #log_warn 'RPM/DEB pkg conflict MAY occur if OS minor version miscmatch! use with caution!'
 fi
 
 
 #--------------------------------------------------------------#
-# Hint
+# Next Hint
 #--------------------------------------------------------------#
-log_line "Reference"
-log_hint "Website:      https://pigsty.io"
-log_hint "Public Demo:  https://demo.pigsty.cc"
-log_hint "Github Repo:  https://github.com/Vonng/pigsty"
+log_line "Todolist"
+log_hint "cd ${INSTALL_TO}"
+log_hint './bootstrap      # [OPTIONAL] install ansible & use offline package'
+log_hint './configure      # [OPTIONAL] preflight-check and config generation'
+log_hint './install.yml    # install pigsty modules according to your config.'
 
-log_line "Proceeding"
-log_hint 'cd ~/pigsty      # entering pigsty home directory before proceeding'
-log_hint './bootstrap      # install ansible & download the optional offline packages'
-log_hint './configure      # preflight-check and generate config according to your env'
-log_hint './install.yml    # install pigsty on this node and init it as the admin node'
-log_info "~/pigsty is ready to go now!"
+log_line "Complete"
+# log_info "pigsty installed, ready for deploying with above command"
